name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Type check
        run: npm run typecheck

      #   - name: Run unit tests
      #     run: npm run test:unit

      #   - name: Install Playwright browsers
      #     run: npx playwright install --with-deps

      # - name: Run E2E tests
      #   run: npm run test:e2e

      - name: Build on GitHub
        if: github.ref == 'refs/heads/main'
        run: npm run build

      - name: Deploy backend files to EC2
        if: github.ref == 'refs/heads/main'
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "index.js,index.html,package.json,package-lock.json"
          target: "/home/${{ secrets.EC2_USERNAME }}/tableau-fields-dependency/"

      - name: Deploy built frontend files to EC2
        if: github.ref == 'refs/heads/main'
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "dist/*"
          target: "/home/${{ secrets.EC2_USERNAME }}/tableau-fields-dependency/dist/"

      - name: Deploy to EC2
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Starting deployment..."
            cd tableau-fields-dependency
            echo "Current directory: $(pwd)"
            echo "Directory contents:"
            ls -la
            echo "Dist directory contents:"
            ls -la dist/
            echo "Installing production dependencies..."
            npm ci --only=production
            sudo systemctl restart tableau-fields-dependency
            echo "Deployment completed"
